/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.shbair.hospital.view;

import com.shbair.hospital.db.dao.PatientinfoDao;
import com.shbair.hospital.db.dao.UserDetailsDao;
import com.shbair.hospital.db.dao.UsersDao;
import com.shbair.hospital.db.type.UsersType;
import com.shbair.hospital.db.vo.PatientinfoVo;
import com.shbair.hospital.db.vo.UserDetailsVo;
import com.shbair.hospital.db.vo.UsersVo;
import com.shbair.hospital.validation.Validation;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LCS
 */
public class PatientinfoView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PatientinfoView.class.getName());
    private int userId;

    /**
     * Creates new form PatientinfoView
     */
    public PatientinfoView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFatherName = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtUserId = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnGetMessage = new javax.swing.JButton();

        jLabel1.setText("ID");

        jLabel2.setText("First Name");

        txtFirstName.addActionListener(this::txtFirstNameActionPerformed);

        jLabel3.setText("Father Name");

        jLabel4.setText("Mobile");

        jLabel5.setText("Email");

        jLabel6.setText("User ID");

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnSelect.setText("Search");
        btnSelect.addActionListener(this::btnSelectActionPerformed);

        btnGetMessage.setText("Get Message");
        btnGetMessage.addActionListener(this::btnGetMessageActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGetMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnAdd)
                        .addGap(27, 27, 27)
                        .addComponent(btnDelete)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnSelect)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnGetMessage)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        boolean isTextEmpty = Validation .isEmpty(txtid.getText(),txtFirstName.getText(),txtFatherName.getText(),txtMobile.getText(),txtEmail.getText(),txtUserId.getText());
        boolean isDigit=Validation.isDigit(txtid.getText(),txtMobile.getText(),txtUserId.getText());
        boolean  isText= Validation.isText(txtFirstName.getText(),txtFatherName.getText(),txtEmail.getText());
         if (isTextEmpty==true ) {
            JOptionPane.showMessageDialog(null,"please enter valid data!!! ");
            return;
        }if (isDigit==false||isText==false) {
            JOptionPane.showMessageDialog(null,"please enter valid data!!! ");
          return;
        }
        int id=Integer.valueOf( txtid.getText());
        String firstName =txtFirstName.getText();
        String fatherName = txtFatherName.getText();
        String mobile=txtMobile.getText();
        String email=txtEmail.getText();
        int userid=Integer.parseInt(txtUserId.getText());
        PatientinfoVo patientinfoVo = new  PatientinfoVo();
        patientinfoVo.setId(id);
        patientinfoVo.setFirstName(firstName);
        patientinfoVo.setFatherName(fatherName);
        patientinfoVo.setMobile(mobile);
        patientinfoVo.setEmail(email);
        UsersVo usersVo =new UsersVo();
        usersVo.setId(userId);
        patientinfoVo.setUsersVo(usersVo);
          try {
      
          int count= PatientinfoDao.getInstance().insert(patientinfoVo);
           
            if (count==1){
            JOptionPane.showMessageDialog(null, "Insert successfully ");
                reset();
            }
           else{
              JOptionPane.showMessageDialog(null,"Insert is not successfully !!! ");
              
            
            }
                    } catch (Exception ex) {
            System.getLogger(UsersView.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        boolean isTextEmpty = Validation .isEmpty(txtid.getText());
        boolean isDigit=Validation.isDigit(txtid.getText());
        if (isTextEmpty==true) {
            JOptionPane.showMessageDialog(null,"please enter valid data!!! ");
            return;
        }if (isDigit==false) {
            JOptionPane.showMessageDialog(null,"please enter valid data!!! ");
          return;
        }
      
        int id =Integer.valueOf( txtid.getText());
       PatientinfoVo patientinfoVo = new PatientinfoVo();
       patientinfoVo.setId(id);
      try {
       PatientinfoVo piv = PatientinfoDao.getInstance().getDataById(id);
          if (piv==null) {
                JOptionPane.showMessageDialog(null,"please enter valid ID!!! ");
              return;
          }
          int count= PatientinfoDao.getInstance().delete(patientinfoVo);
          
            if (count>0)
            {
                JOptionPane.showMessageDialog(null,"deleted  ");
                reset();
            }else{
              JOptionPane.showMessageDialog(null,"delete is not successfully !!! ");
            
            }
                   } catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage());
    ex.printStackTrace();
}
     

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       boolean isTextEmpty = Validation .isEmpty(txtid.getText(),txtFirstName.getText(),txtFatherName.getText(),txtMobile.getText(),txtEmail.getText(),txtUserId.getText());
        boolean isDigit=Validation.isDigit(txtid.getText(),txtMobile.getText(),txtUserId.getText());
        boolean  isText= Validation.isText(txtFirstName.getText(),txtFatherName.getText(),txtEmail.getText());
         if (isTextEmpty==true ) {
            JOptionPane.showMessageDialog(null,"please enter valid data!!! ");
            return;
        }if (isDigit==false||isText==false) {
            JOptionPane.showMessageDialog(null,"please enter valid data!!! ");
          return;
        }
        int id=Integer.valueOf( txtid.getText());
        String firstName =txtFirstName.getText();
        String fatherName = txtFatherName.getText();
        String mobile=txtMobile.getText();
        String email=txtEmail.getText();
        int userid=Integer.parseInt(txtUserId.getText());
        PatientinfoVo patientinfoVo = new  PatientinfoVo();
        patientinfoVo.setId(id);
        patientinfoVo.setFirstName(firstName);
        patientinfoVo.setFatherName(fatherName);
        patientinfoVo.setMobile(mobile);
        patientinfoVo.setEmail(email);
        UsersVo usersVo =new UsersVo();
        usersVo.setId(userId);
        patientinfoVo.setUsersVo(usersVo);
          try {
             PatientinfoVo piv = PatientinfoDao.getInstance().getDataById(id);
          if (piv==null) {
                JOptionPane.showMessageDialog(null,"please enter valid ID!!! ");
              return;
          }
          int count= PatientinfoDao.getInstance().update(patientinfoVo);
           
            if (count==1){
            JOptionPane.showMessageDialog(null, "Update successfully ");
                reset();
            }
           else{
              JOptionPane.showMessageDialog(null,"Update  not successfully !!! ");
              
            
            }
                    } catch (Exception ex) {
            System.getLogger(UsersView.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
    boolean isTextEmpty = Validation.isEmpty(txtid.getText());
    boolean isDigit = Validation.isDigit(txtid.getText());

if (isTextEmpty ==true) {
    JOptionPane.showMessageDialog(null, "Please enter a valid ID!!!");
    return;
}
if (isDigit ==false) {
    JOptionPane.showMessageDialog(null, "Please enter a valid ID!!!");
    return;
}

int id = Integer.parseInt(txtid.getText());

try {
    PatientinfoVo patientinfoVo = PatientinfoDao.getInstance().getDataById(id);

    if (patientinfoVo == null) {
        JOptionPane.showMessageDialog(null, "ID does not exist!");
        reset(); // إعادة تعيين الحقول
    } else {
        // تعبئة الحقول
        txtFirstName.setText(patientinfoVo.getFirstName());
        txtFatherName.setText(patientinfoVo.getFatherName());
        txtMobile.setText(patientinfoVo.getMobile());
        txtEmail.setText(patientinfoVo.getEmail());
        txtUserId.setText(String.valueOf( patientinfoVo.getUsersVo().getId()));

    }
} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
}

        
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnGetMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetMessageActionPerformed
        MessageView messageView =new MessageView();
        messageView.setVisible(true);
    }//GEN-LAST:event_btnGetMessageActionPerformed
     protected void reset(){
    txtid.setText("");
    txtFirstName.setText("");
    txtFatherName.setText("");
    txtMobile.setText("");
    txtEmail.setText("");
    txtUserId.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PatientinfoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnGetMessage;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
