/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.shbair.hospital.view;

import com.shbair.hospital.db.dao.UserDetailsDao;
import com.shbair.hospital.db.dao.UsersDao;
import com.shbair.hospital.db.type.UsersType;
import com.shbair.hospital.db.vo.UserDetailsVo;
import com.shbair.hospital.db.vo.UsersVo;
import com.shbair.hospital.validation.Validation;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.html.HTMLDocument;

/**
 *
 * @author LCS
 */
public class UsersView extends javax.swing.JFrame {
    public static byte []imageByte;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UsersView.class.getName());
    private UserDetailsVo userDetailsVo;

    /**
     * Creates new form UsersView
     */
    public UsersView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cUserType = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFatherName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdite = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtImagePath = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        lblImag = new javax.swing.JLabel();
        cmpSpecialization = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setText("Add");

        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jLabel1.setText("     ID ");

        txtId.addActionListener(this::txtIdActionPerformed);

        jLabel2.setText("User Name");

        txtUserName.addActionListener(this::txtUserNameActionPerformed);

        jLabel3.setText("Password");

        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        jLabel4.setText("User Type");

        cUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "doctor", "nurse", "reception" }));
        cUserType.setSelectedIndex(-1);
        cUserType.addActionListener(this::cUserTypeActionPerformed);

        jLabel5.setText("First Name");

        jLabel6.setText("Father Name");

        jLabel7.setText("Mobile");

        jButton1.setText("Add");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnEdite.setText("Edit");
        btnEdite.addActionListener(this::btnEditeActionPerformed);

        jButton2.setText("Choose Image ");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        cmpSpecialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "giniral ", " " }));
        cmpSpecialization.setSelectedIndex(-1);

        jLabel9.setText("Specialization");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtId)
                    .addComponent(txtUserName)
                    .addComponent(txtPassword)
                    .addComponent(cUserType, 0, 172, Short.MAX_VALUE)
                    .addComponent(txtFirstName)
                    .addComponent(txtFatherName)
                    .addComponent(txtMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(cmpSpecialization, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(txtImagePath)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImage))
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEdite)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(txtImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmpSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblImag, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean isTextEmpty = Validation .isEmpty(txtId.getText(),txtUserName.getText(),txtPassword.getText(),txtFirstName.getText(),txtFatherName.getText(),txtMobile.getText(),txtImagePath.getText());
        boolean isEmpty =  Validation.isEmpty(cUserType.getSelectedIndex(),cmpSpecialization.getSelectedIndex());
        boolean isDigit=Validation.isDigit(txtId.getText(),txtMobile.getText());
        boolean  isText= Validation.isText(txtUserName.getText(),txtPassword.getText(),txtFirstName.getText(),txtFatherName.getText());
         if (isTextEmpty==true || isEmpty==true) {
            JOptionPane.showMessageDialog(null,"please enter valid data!!! ");
            return;
        }if (isDigit==false||isText==false) {
            JOptionPane.showMessageDialog(null,"please enter valid data!!! ");
          return;
        }
        int id =Integer.valueOf( txtId.getText());
        String userName = txtUserName.getText();
        String password = txtPassword.getText();
        UsersType usersType = UsersType.getUsersTypeByType(cUserType.getSelectedItem().toString()); 
        // تعبئة الداتا 
        UsersVo usersVo =new UsersVo();
        usersVo.setId(id);
        usersVo.setUserName(userName);
        usersVo.setPassword(password);
        usersVo.setUsersType(usersType);
        String firstName = txtFirstName.getText();
        String fatherName = txtFatherName.getText();
        String mobile = txtMobile.getText();
        String Specialization = cmpSpecialization.getSelectedItem().toString();
        // تعبئة الداتا 
        UserDetailsVo userDetailsVo = new UserDetailsVo();
        userDetailsVo.setUsersVo(usersVo);
        userDetailsVo.setFirstName(firstName);
        userDetailsVo.setFatherName(fatherName);
        userDetailsVo.setMobile(mobile);
        userDetailsVo.setSpecialization(Specialization);
        userDetailsVo.setImage(imageByte);
        
        
        try {
      
          int count= UserDetailsDao.getInstance().insert(userDetailsVo);
           
            if (count==1){
            JOptionPane.showMessageDialog(null, "Insert successfully ");
                reset();
            }
           else{
              JOptionPane.showMessageDialog(null,"Insert is not successfully !!! ");
              
            
            }
                    } catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage());
    ex.printStackTrace();
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cUserTypeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
                                                                                 
        boolean isTextEmpty = Validation .isEmpty(txtId.getText());
        boolean isDigit=Validation.isDigit(txtId.getText());
        if (isTextEmpty==true) {
            JOptionPane.showMessageDialog(null,"please enter valid data!!! ");
            return;
        }if (isDigit==false) {
            JOptionPane.showMessageDialog(null,"please enter valid data!!! ");
          return;
        }
      
        int id =Integer.valueOf( txtId.getText());
        UsersVo usersVo =new UsersVo();
        usersVo.setId(id);
        UserDetailsVo userDetailsVo = new UserDetailsVo();
        userDetailsVo.setUsersVo(usersVo);
      try {
       UsersVo uv = UsersDao.getInstance().getDataById(id);
          if (uv==null) {
                JOptionPane.showMessageDialog(null,"please enter valid ID!!! ");
              return;
          }
          int count= UserDetailsDao.getInstance().delete(userDetailsVo);
          
            if (count>0)
            {
                JOptionPane.showMessageDialog(null,"delete successfully *_^ ");
                reset();
            }else{
              JOptionPane.showMessageDialog(null,"delete is not successfully !!! ");
            
            }
                   } catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage());
    ex.printStackTrace();
}


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditeActionPerformed
        boolean isTextEmpty = Validation .isEmpty(txtId.getText(),txtUserName.getText(),txtPassword.getText(),txtFirstName.getText(),txtFatherName.getText(),txtMobile.getText());
        boolean isEmpty =  Validation.isEmpty(cUserType.getSelectedIndex());
        boolean isDigit=Validation.isDigit(txtId.getText(),txtMobile.getText());
        boolean  isText= Validation.isText(txtUserName.getText(),txtPassword.getText(),txtFirstName.getText(),txtFatherName.getText());
        if (isTextEmpty==true || isEmpty==true) {
            JOptionPane.showMessageDialog(null,"please enter valid data!!! ");
            return;
        }if (isDigit==false||isText==false) {
            JOptionPane.showMessageDialog(null,"please enter valid data!!! ");
          return;
        }
      
        int id =Integer.valueOf( txtId.getText());
        String userName = txtUserName.getText();
        String password = txtPassword.getText();
        UsersType usersType = UsersType.getUsersTypeByType(cUserType.getSelectedItem().toString());
        // تعبئة الداتا 
        UsersVo usersVo =new UsersVo();
        usersVo.setId(id);
        usersVo.setUserName(userName);
        usersVo.setPassword(password);
        usersVo.setUsersType(usersType);
        String firstName = txtFirstName.getText();
        String fatherName = txtFatherName.getText();
        String mobile = txtMobile.getText();
        // تعبئة الداتا 
        UserDetailsVo userDetailsVo = new UserDetailsVo();
        userDetailsVo.setUsersVo(usersVo);
        userDetailsVo.setFirstName(firstName);
        userDetailsVo.setFatherName(fatherName);
        userDetailsVo.setMobile(mobile);
        userDetailsVo.setImage(imageByte);
        
        
        try {
            UsersVo uv = UsersDao.getInstance().getDataById(id);
            if(uv ==null){
            JOptionPane.showMessageDialog(null,"please enter valid data ");
            return;
            } 
          int count= UserDetailsDao.getInstance().update(userDetailsVo);
          
            if (count==1)
            {
                JOptionPane.showMessageDialog(null,"Update successfully *_^ ");
                reset();
            }else{
              JOptionPane.showMessageDialog(null,"Update is not successfully !!! ");
            
            }
                   } catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex.getMessage());
    ex.printStackTrace();
}

    }//GEN-LAST:event_btnEditeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     JFileChooser jFileChooser=new JFileChooser();
     jFileChooser.showOpenDialog(null);
     File file=jFileChooser.getSelectedFile();
     String ImagePath=file.getAbsolutePath();
     txtImagePath.setText(ImagePath);
        try {
            File file2=new File(ImagePath);
            FileInputStream fis = new FileInputStream(file2);
            ByteArrayOutputStream baos= new ByteArrayOutputStream();
            byte []length=new byte[1024];
            for(int i;(i=fis.read(length))!=-1;){
            baos.write(length,0,i);
            
            }
            imageByte=baos.toByteArray();
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    boolean isTextEmpty = Validation.isEmpty(txtId.getText());
    boolean isDigit = Validation.isDigit(txtId.getText());

if (isTextEmpty || !isDigit) {
    JOptionPane.showMessageDialog(null, "Please enter a valid ID!!!");
    return;
}

int id = Integer.parseInt(txtId.getText());

try {
    UserDetailsVo userDetailsVo = UserDetailsDao.getInstance().getDataById(id);

    if (userDetailsVo == null) {
        JOptionPane.showMessageDialog(null, "ID does not exist!");
        reset(); // إعادة تعيين الحقول
    } else {
        // تعبئة الحقول
        txtUserName.setText(userDetailsVo.getUsersVo().getUserName());
        txtPassword.setText(userDetailsVo.getUsersVo().getPassword());
        txtFirstName.setText(userDetailsVo.getFirstName());
        txtFatherName.setText(userDetailsVo.getFatherName());
        txtMobile.setText(userDetailsVo.getMobile());

        // ضبط ComboBox
        UsersType type = userDetailsVo.getUsersVo().getUsersType();
        if (type != null) {
            cUserType.setSelectedItem(type.getType()); // استخدم getType() من enum
        } else {
            cUserType.setSelectedIndex(0);
        }
        cmpSpecialization.setSelectedItem(userDetailsVo.getSpecialization());

        // عرض الصورة بحجم اللابل
        byte[] imageByte = userDetailsVo.getImage();
        if (imageByte != null && imageByte.length > 0) {
            ImageIcon originalIcon = new ImageIcon(imageByte);
            Image scaledImage = originalIcon.getImage().getScaledInstance(
                lblImag.getWidth(),
                lblImag.getHeight(),
                Image.SCALE_SMOOTH
            );
            lblImag.setIcon(new ImageIcon(scaledImage));
        } else {
            lblImag.setIcon(null);
        }
    }

} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
}

    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    protected void reset(){
    txtId.setText("");
    txtUserName.setText("");
    txtPassword.setText("");
    txtFirstName.setText("");
    txtFatherName.setText("");
    txtMobile.setText("");
    cUserType.setSelectedIndex(-1);
    txtImagePath.setText("");
    lblImag.setIcon(null);
    cmpSpecialization.setSelectedIndex(-1);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UsersView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdite;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cUserType;
    private javax.swing.JComboBox<String> cmpSpecialization;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblImag;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtImagePath;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
